In [1]:
from src.mlcore.dataloader import get_processed_data

raw = get_processed_data(
    source="local",
    symbol="BTCUSDC",
    save_dir="parquets/",
    grid_resolution_ms=5000,
)
raw

,exchange_ts,open,high,low,close,volume,volume_1s,buy_volume_1s,sell_volume_1s,volume_imbalance_1s,...,ask_qty_90,ask_qty_91,ask_qty_92,ask_qty_93,ask_qty_94,ask_qty_95,ask_qty_96,ask_qty_97,ask_qty_98,ask_qty_99
0,2026-01-23 11:50:30,89130.601562,89139.500000,89130.500000,89135.101562,0.769,0.000,0.000,0.000,0.000000,...,0.014,1.000,0.139,0.002,0.005,0.141,1.796,0.821,0.006,0.139
1,2026-01-23 11:50:35,89130.398438,89130.398438,89130.398438,89130.398438,0.002,0.196,0.000,0.196,-1.000000,...,0.139,0.002,0.139,0.744,0.139,1.010,1.796,0.139,0.112,1.139
2,2026-01-23 11:50:40,89130.398438,89130.398438,89130.398438,89130.398438,0.002,0.000,0.000,0.000,0.000000,...,0.020,0.023,0.139,1.094,0.139,1.075,1.796,0.139,1.008,1.139
3,2026-01-23 11:50:45,89130.398438,89130.398438,89128.000000,89128.101562,0.232,0.000,0.000,0.000,0.000000,...,0.002,0.139,1.094,0.139,1.122,1.796,0.139,1.011,0.112,1.307
4,2026-01-23 11:50:50,89128.101562,89128.101562,89128.101562,89128.101562,0.002,0.004,0.000,0.004,-1.000000,...,0.005,0.139,0.415,0.003,0.139,0.004,0.139,0.978,0.139,0.744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851149,2026-03-13 17:59:35,71009.000000,71009.000000,70992.601562,70999.203125,4.246,0.021,0.011,0.010,0.047619,...,2.866,0.212,0.580,0.002,0.018,0.002,0.002,0.631,0.002,4.023
851150,2026-03-13 17:59:40,70993.203125,71000.203125,70991.101562,70997.296875,3.054,0.460,0.214,0.246,-0.069565,...,0.002,2.593,2.154,4.041,0.002,0.003,1.438,0.034,0.027,0.140
851151,2026-03-13 17:59:45,70995.000000,70996.296875,70990.101562,70996.296875,1.782,0.000,0.000,0.000,0.000000,...,0.006,0.140,0.732,0.027,0.002,0.002,0.018,0.022,0.002,0.735
851152,2026-03-13 17:59:50,70983.500000,70993.500000,70983.398438,70985.601562,4.335,0.554,0.003,0.551,-0.989170,...,0.105,0.004,0.009,0.002,0.003,0.002,0.009,0.009,0.002,0.038
851153,2026-03-13 17:59:55,71017.898438,71022.500000,70988.398438,71003.203125,10.619,0.022,0.022,0.000,1.000000,...,0.123,0.721,0.002,0.038,0.008,0.004,0.861,0.024,0.004,0.004

In [2]:
from src.mlcore.dataloader import calculate_features

df = calculate_features(raw, filename='all_features')
df['open'] = raw['open']
df['high'] = raw['high']
df['low'] = raw['low']
df['close'] = raw['close']
df['volume'] = raw['volume']
df.dropna(inplace=True)
df

,adverse_selection_risk,ask_price_pressure,atr,atr_exponential_smoothing_alpha_0_8,bid_ask_cancellation_proxy5,bid_ask_spread_tightness_index,bid_price_pressure,combo16_weighted_orderbook_log_times_slope,combo29_response_imbalance_log1p_times_wli,combo35_fqi_rolling_std_18_times_slope,...,volatility_contraction_expansion_ratio,weighted_depth_ratio,weighted_log_imbalance_5levels,weighted_orderbook_imbalance,weighted_price_pressure,open,high,low,close,volume
30,1.720052,4.470000,4.350781,4.826048,1.591322e-04,1.720241,0.399000,-0.282542,-0.043540,-3.870383,...,0.141357,0.862152,-0.825813,-0.537971,-0.540668,89150.796875,89150.796875,89142.398438,89145.703125,0.276
31,1.673307,0.248484,4.208880,4.584924,2.141049e-04,1.673463,0.588047,3.569189,0.434759,32.839458,...,0.134234,4.493296,4.811982,0.943113,0.945398,89145.796875,89145.796875,89145.796875,89145.796875,0.026
32,1.826563,0.965219,4.068584,4.278148,2.752305e-04,1.826706,0.176813,2.594957,0.397548,28.002368,...,0.134234,3.452995,3.723537,0.751790,0.752639,89145.796875,89145.796875,89145.796875,89145.796875,0.026
33,1.826563,0.026508,3.932965,3.976710,4.429674e-04,1.826679,0.055969,0.989410,0.123907,17.214146,...,0.130717,2.117040,2.170741,0.394916,0.393676,89145.796875,89145.796875,89145.796875,89145.796875,0.026
34,1.788281,0.026914,3.955251,3.956434,9.560574e-04,1.788374,0.056250,0.976829,0.122001,16.139879,...,0.137894,2.066252,2.160544,0.390597,0.389091,89150.296875,89150.398438,89150.296875,89150.398438,0.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851149,15.120052,0.727109,28.335883,26.318453,1.046618e-07,15.120031,0.218055,1.654551,0.780759,30.181990,...,0.987970,2.747221,2.771074,0.658527,0.662684,71009.000000,71009.000000,70992.601562,70999.203125,4.246
851150,15.190104,0.221625,27.694739,25.191401,1.720900e-07,15.190083,0.824578,-4.474389,-1.898496,-68.310877,...,0.981137,0.103314,-5.772870,-0.788561,-0.789059,70993.203125,71000.203125,70991.101562,70997.296875,3.054
851151,15.283594,0.149906,27.011424,23.953744,3.845789e-07,15.283572,0.876000,-2.552467,-1.147343,-46.818383,...,0.978335,0.877376,-3.972621,-0.672821,-0.680746,70995.000000,70996.296875,70990.101562,70996.296875,1.782
851152,15.603516,3.122555,26.540992,23.092161,2.010351e-06,15.603494,0.355406,-0.100549,-0.012960,-29.135864,...,0.990605,0.507533,-2.032838,-0.031374,0.004980,70983.500000,70993.500000,70983.398438,70985.601562,4.335
851153,15.383594,0.051648,26.886240,23.721083,5.356517e-07,15.383572,0.057078,0.636811,0.902096,10.891872,...,0.990318,1.907699,2.297841,0.720620,0.938586,71017.898438,71022.500000,70988.398438,71003.203125,10.619

In [3]:
feature_columns = [col for col in df.columns if col not in ['open', 'high', 'low', 'close', 'volume']]
X = df[feature_columns].copy()
ohlcv = df[['open', 'high', 'low', 'close', 'volume']].copy()

split_index = int(len(X) * 0.8)
_, X_test = X.iloc[:split_index], X.iloc[split_index:]
_, ohlcv_test = ohlcv.iloc[:split_index], ohlcv.iloc[split_index:]

In [4]:
from xgboost import XGBRegressor
from src.trading.backtest_trader import BacktestTrader

mid_model = XGBRegressor()
mid_model._estimator_type = "regressor"
mid_model.load_model('models/model_mid.json')

spread_model = XGBRegressor()
spread_model._estimator_type = "regressor"
spread_model.load_model('models/model_spread.json')

mid_pred = mid_model.predict(X_test)
spread_pred = spread_model.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt
from src.trading.backtest_trader import BacktestTrader, optimize_parameters_fast, optimize_parameters

bt = BacktestTrader(
    alpha=8.315871824518858,
    beta=3.7732988233597897,
    gamma=0.05385359393345956,
    epsilon=0.0,
    max_position=0.07,
    position_qty=0.002,
)

# bar_seconds должен соответствовать сетке данных: 5000 ms -> 5.0, 1000 ms -> 1.0
results = bt.run(
    ohlcv=ohlcv_test,
    mid_predicts=mid_pred,
    spread_predicts=spread_pred,
    position_size=100.0,
    bar_seconds=5.0,
)
print(f"Sharpe: {results['sharpe_ratio']}")
plt.figure(figsize=(14,7))
plt.plot(results['bh_curve'], color="black")
plt.plot(results['realized_pnl_curve'], color="red")
plt.grid()
plt.show()
plt.figure(figsize=(14, 7))
plt.plot(results['position_curve'], color="blue")
plt.grid()
plt.show()

Sharpe: 9.118589812717465

### Bayessian Optimization

In [ ]:
opt_results = optimize_parameters_fast(
    ohlcv=ohlcv_test,
    mid_predicts=mid_pred,
    spread_predicts=spread_pred,
    position_size=100.0,
    max_position=0.06,
    position_qty=0.002,
    alpha_range=(-10, 10),
    beta_range=(-10, 10),
    gamma_range=(0, 1),
    epsilon_range=(0, 0.01),
    n_calls=300,
    n_initial_points=100,
)

opt_results

Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 2.1325
Function value obtained: 35.7263
Current minimum: 35.7263
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 2.7235
Function value obtained: 224.4668
Current minimum: 35.7263
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 2.2628
Function value obtained: 127.1634
Current minimum: 35.7263
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 2.6901
Function value obtained: 29.3536
Current minimum: 29.3536
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 2.4153
Function value obtained: 80.2640
Current minimum: 29.3536
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 2.2150
Function value obtained: 307.9282
Current minimum: 29.3536
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 2.1144
Function value obtained: 338.4683
Current minimum: 29.3536
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 2.0842
Function value obtained: 283.4968
Current minimum: 29.3536
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 2.3733
Function value obtained: 219.1000
Current minimum: 29.3536
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 2.1191
Function value obtained: 202.1485
Current minimum: 29.3536
Iteration No: 11 started. Evaluating function at random point.
Iteration No: 11 ended. Evaluation done at random point.
Time taken: 2.0459
Function value obtained: 28.0756
Current minimum: 28.0756
Iteration No: 12 started. Evaluating function at random point.
Iteration No: 12 ended. Evaluation done at random point.
Time taken: 2.5778
Function value obtained: 256.3036
Current minimum: 28.0756
Iteration No: 13 started. Evaluating function at random point.
Iteration No: 13 ended. Evaluation done at random point.
Time taken: 2.1994
Function value obtained: 224.3835
Current minimum: 28.0756
Iteration No: 14 started. Evaluating function at random point.
Iteration No: 14 ended. Evaluation done at random point.
Time taken: 2.1530
Function value obtained: 266.2371
Current minimum: 28.0756
Iteration No: 15 started. Evaluating function at random point.
Iteration No: 15 ended. Evaluation done at random point.
Time taken: 1.9951
Function value obtained: 174.5039
Current minimum: 28.0756
Iteration No: 16 started. Evaluating function at random point.
Iteration No: 16 ended. Evaluation done at random point.
Time taken: 1.9841
Function value obtained: -4.0583
Current minimum: -4.0583
Iteration No: 17 started. Evaluating function at random point.
Iteration No: 17 ended. Evaluation done at random point.
Time taken: 2.6452
Function value obtained: 92.7162
Current minimum: -4.0583
Iteration No: 18 started. Evaluating function at random point.
Iteration No: 18 ended. Evaluation done at random point.
Time taken: 2.0791
Function value obtained: 349.8091
Current minimum: -4.0583
Iteration No: 19 started. Evaluating function at random point.
Iteration No: 19 ended. Evaluation done at random point.
Time taken: 2.0747
Function value obtained: 312.7619
Current minimum: -4.0583
Iteration No: 20 started. Evaluating function at random point.
Iteration No: 20 ended. Evaluation done at random point.
Time taken: 1.9626
Function value obtained: 77.6421
Current minimum: -4.0583
Iteration No: 21 started. Evaluating function at random point.
Iteration No: 21 ended. Evaluation done at random point.
Time taken: 2.0863
Function value obtained: -4.8162
Current minimum: -4.8162
Iteration No: 22 started. Evaluating function at random point.
Iteration No: 22 ended. Evaluation done at random point.
Time taken: 1.9490
Function value obtained: 18.0935
Current minimum: -4.8162
Iteration No: 23 started. Evaluating function at random point.
Iteration No: 23 ended. Evaluation done at random point.
Time taken: 2.0254
Function value obtained: 313.3334
Current minimum: -4.8162
Iteration No: 24 started. Evaluating function at random point.
Iteration No: 24 ended. Evaluation done at random point.
Time taken: 1.9540
Function value obtained: 26.1283
Current minimum: -4.8162
Iteration No: 25 started. Evaluating function at random point.
Iteration No: 25 ended. Evaluation done at random point.
Time taken: 1.9961
Function value obtained: 53.8378
Current minimum: -4.8162
Iteration No: 26 started. Evaluating function at random point.
Iteration No: 26 ended. Evaluation done at random point.
Time taken: 1.9617
Function value obtained: -3.5638
Current minimum: -4.8162
Iteration No: 27 started. Evaluating function at random point.
Iteration No: 27 ended. Evaluation done at random point.
Time taken: 2.0024
Function value obtained: 399.0765
Current minimum: -4.8162
Iteration No: 28 started. Evaluating function at random point.
Iteration No: 28 ended. Evaluation done at random point.
Time taken: 1.9187
Function value obtained: -3.9966
Current minimum: -4.8162
Iteration No: 29 started. Evaluating function at random point.
Iteration No: 29 ended. Evaluation done at random point.
Time taken: 1.9832
Function value obtained: 47.0995
Current minimum: -4.8162
Iteration No: 30 started. Evaluating function at random point.
Iteration No: 30 ended. Evaluation done at random point.
Time taken: 2.0785
Function value obtained: 509.8709
Current minimum: -4.8162
Iteration No: 31 started. Evaluating function at random point.
Iteration No: 31 ended. Evaluation done at random point.
Time taken: 2.4012
Function value obtained: 466.5417
Current minimum: -4.8162
Iteration No: 32 started. Evaluating function at random point.
Iteration No: 32 ended. Evaluation done at random point.
Time taken: 2.0049
Function value obtained: 92.5878
Current minimum: -4.8162
Iteration No: 33 started. Evaluating function at random point.
Iteration No: 33 ended. Evaluation done at random point.
Time taken: 2.4199
Function value obtained: 435.5353
Current minimum: -4.8162
Iteration No: 34 started. Evaluating function at random point.
Iteration No: 34 ended. Evaluation done at random point.
Time taken: 2.0340
Function value obtained: 181.2284
Current minimum: -4.8162
Iteration No: 35 started. Evaluating function at random point.
Iteration No: 35 ended. Evaluation done at random point.
Time taken: 1.9659
Function value obtained: 98.2721
Current minimum: -4.8162
Iteration No: 36 started. Evaluating function at random point.
Iteration No: 36 ended. Evaluation done at random point.
Time taken: 2.0543
Function value obtained: 386.6499
Current minimum: -4.8162
Iteration No: 37 started. Evaluating function at random point.
Iteration No: 37 ended. Evaluation done at random point.
Time taken: 2.0479
Function value obtained: -0.5634
Current minimum: -4.8162
Iteration No: 38 started. Evaluating function at random point.
Iteration No: 38 ended. Evaluation done at random point.
Time taken: 2.1552
Function value obtained: 384.8072
Current minimum: -4.8162
Iteration No: 39 started. Evaluating function at random point.
Iteration No: 39 ended. Evaluation done at random point.
Time taken: 1.9772
Function value obtained: 369.6960
Current minimum: -4.8162
Iteration No: 40 started. Evaluating function at random point.
Iteration No: 40 ended. Evaluation done at random point.
Time taken: 2.2058
Function value obtained: 251.4517
Current minimum: -4.8162
Iteration No: 41 started. Evaluating function at random point.
Iteration No: 41 ended. Evaluation done at random point.
Time taken: 2.1472
Function value obtained: 165.1131
Current minimum: -4.8162
Iteration No: 42 started. Evaluating function at random point.
Iteration No: 42 ended. Evaluation done at random point.
Time taken: 2.1290
Function value obtained: 29.6284
Current minimum: -4.8162
Iteration No: 43 started. Evaluating function at random point.
Iteration No: 43 ended. Evaluation done at random point.
Time taken: 1.9622
Function value obtained: 0.9964
Current minimum: -4.8162
Iteration No: 44 started. Evaluating function at random point.
Iteration No: 44 ended. Evaluation done at random point.
Time taken: 2.0044
Function value obtained: 2.4844
Current minimum: -4.8162
Iteration No: 45 started. Evaluating function at random point.
Iteration No: 45 ended. Evaluation done at random point.
Time taken: 2.0652
Function value obtained: 560.0929
Current minimum: -4.8162
Iteration No: 46 started. Evaluating function at random point.
Iteration No: 46 ended. Evaluation done at random point.
Time taken: 1.9853
Function value obtained: 42.6010
Current minimum: -4.8162
Iteration No: 47 started. Evaluating function at random point.
Iteration No: 47 ended. Evaluation done at random point.
Time taken: 2.0860
Function value obtained: 359.6188
Current minimum: -4.8162
Iteration No: 48 started. Evaluating function at random point.
Iteration No: 48 ended. Evaluation done at random point.
Time taken: 2.4192
Function value obtained: 290.3857
Current minimum: -4.8162
Iteration No: 49 started. Evaluating function at random point.
Iteration No: 49 ended. Evaluation done at random point.
Time taken: 1.9445
Function value obtained: 10.1462
Current minimum: -4.8162
Iteration No: 50 started. Evaluating function at random point.
Iteration No: 50 ended. Evaluation done at random point.
Time taken: 2.1592
Function value obtained: 13.1327
Current minimum: -4.8162
Iteration No: 51 started. Evaluating function at random point.
Iteration No: 51 ended. Evaluation done at random point.
Time taken: 1.9247
Function value obtained: 14.5820
Current minimum: -4.8162
Iteration No: 52 started. Evaluating function at random point.
Iteration No: 52 ended. Evaluation done at random point.
Time taken: 2.0208
Function value obtained: 227.8996
Current minimum: -4.8162
Iteration No: 53 started. Evaluating function at random point.
Iteration No: 53 ended. Evaluation done at random point.
Time taken: 2.0514
Function value obtained: 305.7957
Current minimum: -4.8162
Iteration No: 54 started. Evaluating function at random point.
Iteration No: 54 ended. Evaluation done at random point.
Time taken: 2.2686
Function value obtained: 1.7088
Current minimum: -4.8162
Iteration No: 55 started. Evaluating function at random point.
Iteration No: 55 ended. Evaluation done at random point.
Time taken: 2.0815
Function value obtained: 434.5439
Current minimum: -4.8162
Iteration No: 56 started. Evaluating function at random point.
Iteration No: 56 ended. Evaluation done at random point.
Time taken: 2.0166
Function value obtained: 436.9671
Current minimum: -4.8162
Iteration No: 57 started. Evaluating function at random point.
Iteration No: 57 ended. Evaluation done at random point.
Time taken: 2.1355
Function value obtained: 549.9408
Current minimum: -4.8162
Iteration No: 58 started. Evaluating function at random point.
Iteration No: 58 ended. Evaluation done at random point.
Time taken: 1.9668
Function value obtained: -3.9132
Current minimum: -4.8162
Iteration No: 59 started. Evaluating function at random point.
Iteration No: 59 ended. Evaluation done at random point.
Time taken: 1.9617
Function value obtained: 16.2465
Current minimum: -4.8162
Iteration No: 60 started. Evaluating function at random point.
Iteration No: 60 ended. Evaluation done at random point.
Time taken: 1.9444
Function value obtained: 39.9198
Current minimum: -4.8162
Iteration No: 61 started. Evaluating function at random point.
Iteration No: 61 ended. Evaluation done at random point.
Time taken: 2.0497
Function value obtained: 401.7681
Current minimum: -4.8162
Iteration No: 62 started. Evaluating function at random point.
Iteration No: 62 ended. Evaluation done at random point.
Time taken: 1.9726
Function value obtained: -2.9906
Current minimum: -4.8162
Iteration No: 63 started. Evaluating function at random point.
Iteration No: 63 ended. Evaluation done at random point.
Time taken: 1.9635
Function value obtained: 7.5025
Current minimum: -4.8162
Iteration No: 64 started. Evaluating function at random point.
Iteration No: 64 ended. Evaluation done at random point.
Time taken: 2.0358
Function value obtained: 383.1098
Current minimum: -4.8162
Iteration No: 65 started. Evaluating function at random point.
Iteration No: 65 ended. Evaluation done at random point.
Time taken: 1.9099
Function value obtained: 6.6747
Current minimum: -4.8162
Iteration No: 66 started. Evaluating function at random point.
Iteration No: 66 ended. Evaluation done at random point.
Time taken: 2.0009
Function value obtained: 26.4864
Current minimum: -4.8162
Iteration No: 67 started. Evaluating function at random point.
Iteration No: 67 ended. Evaluation done at random point.
Time taken: 2.0247
Function value obtained: 113.4853
Current minimum: -4.8162
Iteration No: 68 started. Evaluating function at random point.
Iteration No: 68 ended. Evaluation done at random point.
Time taken: 2.0373
Function value obtained: 210.8678
Current minimum: -4.8162
Iteration No: 69 started. Evaluating function at random point.
Iteration No: 69 ended. Evaluation done at random point.
Time taken: 1.9869
Function value obtained: 73.9516
Current minimum: -4.8162
Iteration No: 70 started. Evaluating function at random point.
Iteration No: 70 ended. Evaluation done at random point.
Time taken: 2.1261
Function value obtained: 205.0357
Current minimum: -4.8162
Iteration No: 71 started. Evaluating function at random point.
Iteration No: 71 ended. Evaluation done at random point.
Time taken: 1.9705
Function value obtained: 22.4952
Current minimum: -4.8162
Iteration No: 72 started. Evaluating function at random point.
Iteration No: 72 ended. Evaluation done at random point.
Time taken: 2.2519
Function value obtained: 28.1668
Current minimum: -4.8162
Iteration No: 73 started. Evaluating function at random point.
Iteration No: 73 ended. Evaluation done at random point.
Time taken: 1.9745
Function value obtained: 8.2948
Current minimum: -4.8162
Iteration No: 74 started. Evaluating function at random point.
Iteration No: 74 ended. Evaluation done at random point.
Time taken: 2.0221
Function value obtained: 371.4883
Current minimum: -4.8162
Iteration No: 75 started. Evaluating function at random point.
Iteration No: 75 ended. Evaluation done at random point.
Time taken: 2.0140
Function value obtained: 184.9691
Current minimum: -4.8162
Iteration No: 76 started. Evaluating function at random point.
Iteration No: 76 ended. Evaluation done at random point.
Time taken: 2.0426
Function value obtained: 451.3942
Current minimum: -4.8162
Iteration No: 77 started. Evaluating function at random point.
Iteration No: 77 ended. Evaluation done at random point.
Time taken: 2.0103
Function value obtained: 244.8566
Current minimum: -4.8162
Iteration No: 78 started. Evaluating function at random point.
Iteration No: 78 ended. Evaluation done at random point.
Time taken: 2.0492
Function value obtained: 483.9126
Current minimum: -4.8162
Iteration No: 79 started. Evaluating function at random point.
Iteration No: 79 ended. Evaluation done at random point.
Time taken: 2.1322
Function value obtained: 214.7079
Current minimum: -4.8162
Iteration No: 80 started. Evaluating function at random point.
Iteration No: 80 ended. Evaluation done at random point.
Time taken: 2.0310
Function value obtained: 194.0488
Current minimum: -4.8162
Iteration No: 81 started. Evaluating function at random point.
Iteration No: 81 ended. Evaluation done at random point.
Time taken: 2.0561
Function value obtained: 354.9267
Current minimum: -4.8162
Iteration No: 82 started. Evaluating function at random point.
Iteration No: 82 ended. Evaluation done at random point.
Time taken: 2.1240
Function value obtained: 327.8386
Current minimum: -4.8162
Iteration No: 83 started. Evaluating function at random point.
Iteration No: 83 ended. Evaluation done at random point.
Time taken: 2.4411
Function value obtained: 252.4669
Current minimum: -4.8162
Iteration No: 84 started. Evaluating function at random point.
Iteration No: 84 ended. Evaluation done at random point.
Time taken: 2.1372
Function value obtained: 153.1664
Current minimum: -4.8162
Iteration No: 85 started. Evaluating function at random point.
Iteration No: 85 ended. Evaluation done at random point.
Time taken: 3.0169
Function value obtained: 3.2385
Current minimum: -4.8162
Iteration No: 86 started. Evaluating function at random point.
Iteration No: 86 ended. Evaluation done at random point.
Time taken: 2.8213
Function value obtained: 7.0416
Current minimum: -4.8162
Iteration No: 87 started. Evaluating function at random point.
Iteration No: 87 ended. Evaluation done at random point.
Time taken: 2.8162
Function value obtained: 292.9751
Current minimum: -4.8162
Iteration No: 88 started. Evaluating function at random point.
Iteration No: 88 ended. Evaluation done at random point.
Time taken: 2.1067
Function value obtained: 205.6955
Current minimum: -4.8162
Iteration No: 89 started. Evaluating function at random point.
Iteration No: 89 ended. Evaluation done at random point.
Time taken: 2.3987
Function value obtained: 14.8730
Current minimum: -4.8162
Iteration No: 90 started. Evaluating function at random point.
Iteration No: 90 ended. Evaluation done at random point.
Time taken: 2.0823
Function value obtained: -3.9743
Current minimum: -4.8162
Iteration No: 91 started. Evaluating function at random point.
Iteration No: 91 ended. Evaluation done at random point.
Time taken: 2.5369
Function value obtained: 226.3536
Current minimum: -4.8162
Iteration No: 92 started. Evaluating function at random point.
Iteration No: 92 ended. Evaluation done at random point.
Time taken: 2.0778
Function value obtained: 51.7644
Current minimum: -4.8162
Iteration No: 93 started. Evaluating function at random point.
Iteration No: 93 ended. Evaluation done at random point.
Time taken: 2.0528
Function value obtained: 230.9735
Current minimum: -4.8162
Iteration No: 94 started. Evaluating function at random point.
Iteration No: 94 ended. Evaluation done at random point.
Time taken: 1.9941
Function value obtained: 114.9067
Current minimum: -4.8162
Iteration No: 95 started. Evaluating function at random point.
Iteration No: 95 ended. Evaluation done at random point.
Time taken: 2.0165
Function value obtained: 27.2402
Current minimum: -4.8162
Iteration No: 96 started. Evaluating function at random point.
Iteration No: 96 ended. Evaluation done at random point.
Time taken: 1.9842
Function value obtained: 44.4986
Current minimum: -4.8162
Iteration No: 97 started. Evaluating function at random point.
Iteration No: 97 ended. Evaluation done at random point.
Time taken: 2.0739
Function value obtained: 207.3745
Current minimum: -4.8162
Iteration No: 98 started. Evaluating function at random point.
Iteration No: 98 ended. Evaluation done at random point.
Time taken: 2.1902
Function value obtained: 145.0092
Current minimum: -4.8162
Iteration No: 99 started. Evaluating function at random point.
Iteration No: 99 ended. Evaluation done at random point.
Time taken: 2.1409
Function value obtained: 526.2448
Current minimum: -4.8162
Iteration No: 100 started. Evaluating function at random point.
Iteration No: 100 ended. Evaluation done at random point.
Time taken: 2.9169
Function value obtained: 409.6870
Current minimum: -4.8162
Iteration No: 101 started. Searching for the next optimal point.
Iteration No: 101 ended. Search finished for the next optimal point.
Time taken: 2.8402
Function value obtained: 5.3644
Current minimum: -4.8162

{'best_params': {'alpha': 8.315871824518858,
  'beta': 3.7732988233597897,
  'gamma': 0.05385359393345956,
  'epsilon': 0.0},
 'best_sharpe': np.float64(9.118589812717465),
 'best_results': {'bh_curve': [0.0,
   0.007366373976069873,
   0.011935827833098323,
   0.014732747952139746,
   0.0,
   0.00294654959043239,
   0.025344930461423942,
   0.05024097250869719,
   0.04110206479461809,
   0.057158458070594165,
   0.08367740438446347,
   0.09104377836053335,
   0.08515067917969077,
   0.07940720947021696,
   0.07852094260121234,
   0.08972013303671922,
   0.09355294949613402,
   0.1085849563910557,
   0.1380504522953574,
   0.1390748386764118,
   0.11786198361718458,
   0.11550244195297488,
   0.12198254906004014,
   0.11049560964111471,
   0.13701455595498402,
   0.14158400981201247,
   0.14997477016913674,
   0.16883959352347322,
   0.15646638723554318,
   0.15631675776415221,
   0.1549931124403381,
   0.1390748386764118,
   0.14689010106665457,
   0.14717785005009532,
   0.14158400981201247,
   0.14880075431669137,
   0.15027402911191867,
   0.1467404715952636,
   0.1467404715952636,
   0.1592633073545846,
   0.1694266014496959,
   0.15764040308798855,
   0.1717861431139056,
   0.1632342433260714,
   0.16839070510932252,
   0.17679297542576577,
   0.17679297542576577,
   0.18357234147563517,
   0.19447227296836012,
   0.19535853983734253,
   0.17944026607343844,
   0.17679297542576577,
   0.1679533266544908,
   0.1505732880546784,
   0.13391837689316066,
   0.11933525841238968,
   0.11948488788378064,
   0.1028299767222629,
   0.1028299767222629,
   0.09134303730331528,
   0.10798643850551404,
   0.10651316371028674,
   0.08103011373681301,
   0.028878487978079015,
   -0.031238029642288723,
   -0.014882377423541815,
   0.024309034121050566,
   0.041251694266009054,
   0.0472944229182648,
   0.060553896075199454,
   0.04537225970888681,
   0.06835764850610104,
   0.07234009443690681,
   0.060841645058640204,
   0.07351411028935217,
   0.07764618569154891,
   0.07764618569154891,
   0.08751022084390048,
   0.09517585376275228,
   0.09517585376275228,
   0.10180559034120851,
   0.11034598016972375,
   0.11034598016972375,
   0.11595133036714778,
   0.13259473156932433,
   0.13627791855737037,
   0.13937409761919373,
   0.14717785005009532,
   0.147764857976318,
   0.16147321954740335,
   0.18666852053745853,
   0.1679533266544908,
   0.18695626952089928,
   0.18710589899229024,
   0.18415934940185785,
   0.17163651364251464,
   0.16810295612588178,
   0.16810295612588178,
   0.16810295612588178,
   0.17267240998291022,
   0.17281052949496,
   0.1887288032588863,
   0.17296015896635097,
   0.1791525170899977,
   0.1868066400495083,
   0.19564628882078328,
   0.19564628882078328,
   0.20389892966585776,
   0.19490965142319183,
   0.20625847133006747,
   0.17104950571631417,
   0.16898922299486419,
   0.16500677706405842,
   0.16500677706405842,
   0.17104950571631417,
   0.16338387279746236,
   0.15586786935000152,
   0.17973952501619817,
   0.1825364451352396,
   0.1825364451352396,
   0.1834227120042442,
   0.18548299472567198,
   0.18327308253285324,
   0.18548299472567198,
   0.19078908598031408,
   0.1670670597854862,
   0.1708998762449232,
   0.16500677706405842,
   0.16574341446167207,
   0.1573411441452066,
   0.1573411441452066,
   0.15116029598090108,
   0.14173363928340343,
   0.12906117405269146,
   0.1327443610407153,
   0.13333136896693798,
   0.12685126185987272,
   0.12124591166244869,
   0.10180559034120851,
   0.1028299767222629,
   0.11049560964111471,
   0.11049560964111471,
   0.1365771775001523,
   0.14880075431669137,
   0.13348099843832895,
   0.12685126185987272,
   0.10696205212445964,
   0.09134303730331528,
   0.10739943057929136,
   0.12198254906004014,
   0.1356909106311477,
   0.14541682627142727,
   0.15410684557133347,
   0.1520465628499057,
   0.16485714759266745,
   0.1433450335906583,
   0.15263357077612838,
   0.1776792422947704,
   0.1670670597854862,
   0.15322057870232886,
   0.1507114075667504,
   0.16191059800223506,
   0.16574341446167207,
   0.16574341446167207,
   0.17075024677353223,
   0.14983665065708696,
   0.14275802566445783,
   0.1448183083858856,
   0.13303211002415605,
   0.15410684557133347,
   0.15558012036656077,
   0.1762059674995653,
   0.1959455477635652,
   0.19196310183275944,
   0.16515640653544938,
   0.160287693735639,
   0.1433450335906583,
   0.13348099843832895,
   0.12685126185987272,
   0.12375508279804937,
   0.1149154340267522,
   0.12154517060523062,
   0.14555494578347705,
   0.19152572337792773,
   0.13686492648359305,
   0.1259649949908681,
   0.11476580455536123,
   0.13539165168836576,
   0.13731381489774375,
   0.1395237270905847,
   0.15263357077612838,
   0.16441976913783574,
   0.16912734250691397,
   0.16500677706405842,
   0.15660450674759296,
   0.15218468236195548,
   0.1723731510401283,
   0.17649371648300605,
   0.18062579188520278,
   0.18062579188520278,
   0.191088344923096,
   0.20257528434204364,
   0.20493482600625335,
   0.21067829571572716,
   0.2177454107490151,
   0.20920502092049986,
   0.2215782272084299,
   0.20816912458012649,
   0.19711956361601057,
   0.20625847133006747,
   0.21568512802758733,
   0.22142859773703893,
   0.21804466969179703,
   0.21804466969179703,
   0.23247815870115485,
   0.2298308680535044,
   0.21804466969179703,
   0.2046355670634714,
   0.2046355670634714,
   0.1974188225587925,
   0.20331192173963508,
   0.20478519653486238,
   0.20640810080145844,
   0.19859283841121567,
   0.20625847133006747,
   0.20773174612529477,
   0.20773174612529477,
   0.21245082945371419,
   0.21509812010136464,
   0.2177454107490151,
   0.2245247767988623,
   0.2330766765867187,
   0.22556067313925787,
   0.2389697757675835,
   0.24559951234603972,
   0.25222924892451815,
   0.25988337188402877,
   0.2495704483175265,
   0.25767345969121,
   0.2650398336672799,
   0.25885898550297437,
   0.2254110436678669,
   0.21230119998232322,
   0.2046355670634714,
   0.21009128778950448,
   0.1974188225587925,
   0.2090553914491089,
   0.21392410424891928,
   0.2177454107490151,
   0.2177454107490151,
   0.21951794448700213,
   0.2283575932582993,
   0.2292438601272817,
   0.24058117007483837,
   0.24176669588662492,
   0.24441398653427537,
   0.24839643246508114,
   0.2688726501266947,
   0.2592963639578061,
   0.22556067313925787,
   0.2298308680535044,
   0.2254110436678669,
   0.22231486460604355,
   0.2090553914491089,
   0.18990281911133167,
   0.19845471889916588,
   0.19579591829217424,
   0.20242565487065267,
   0.2120019410395413,
   0.21406222376096906,
   0.2177454107490151,
   0.2177454107490151,
   0.21789504022040607,
   0.2206919603394475,
   0.22216523513465258,
   0.22216523513465258,
   0.2298308680535044,
   0.2355743377629782,
   0.24014379162000665,
   0.24014379162000665,
   0.24014379162000665,
   0.2385208873534106,
   0.23395143349638214,
   0.24014379162000665,
   0.24014379162000665,
   0.24014379162000665,
   0.2292438601272817,
   0.22084158981083846,
   0.2177454107490151,
   0.22084158981083846,
   0.20389892966585776,
   0.1940348945135284,
   0.20168901747303902,
   0.2022760253992617,
   0.20316229226824412,
   0.20316229226824412,
   0.20257528434204364,
   0.20257528434204364,
   0.20257528434204364,
   0.18961507012789092,
   0.17340904738052387,
   0.1791525170899977,
   0.1810631703400345,
   0.15646638723554318,
   0.15646638723554318,
   0.15646638723554318,
   0.19152572337792773,
   0.18651889106606756,
   0.16058695267842094,
   0.160287693735639,
   0.1742838042901873,
   0.18695626952089928,
   0.18695626952089928,
   0.2056714634038448,
   0.21230119998232322,
   0.21230119998232322,
   0.22614768106548055,
   0.2283575932582993,
   0.23277741764393678,
   0.22246449407743452,
   0.2052225749896941,
   0.20404855913724873,
   0.21760729123696532,
   0.2052225749896941,
   0.2052225749896941,
   0.20434781808003066,
   0.20773174612529477,
   0.2090553914491089,
   0.20773174612529477,
   0.20773174612529477,
   0.20183864694443,
   0.18842954431610437,
   0.17060061730214127,
   0.20625847133006747,
   0.2622429135482385,
   0.36610878661087476,
   0.47424485458777976,
   0.5215392775060446,
   0.5548375898697611,
   0.5701573457481235,
   0.590633563409737,
   0.6532477422063865,
   0.7012788025222427,
   0.7547540736048131,
   0.7885012743827025,
   0.8189911566680363,
   0.8724779377099479,
   0.9014945452000767,
   0.8898579763097381,
   0.8456597324532966,
   0.8453604735105147,
   0.873651953562371,
   0.8692321291767335,
   0.8471330072485017,
   0.815894977606213,
   0.7994012058754274,
   0.8094148704991477,
   0.7814226493900733,
   0.7526937908833853,
   0.7631563439212785,
   0.7770028250044136,
   0.7407579630502648,
   0.6651835700394848,
   0.6009464869762615,
   0.581943544109853,
   0.5623535933172219,
   0.5362720254581843,
   0.5663245292887087,
   0.5614673264482395,
   0.5203652616535992,
   0.5280193846131098,
   0.5334751053391429,
   0.5275820061582781,
   0.5124003697919655,
   0.49030124786375584,
   0.5350980096057611,
   0.5510047734103463,
   0.5421651246390491,
   0.5778229786669753,
   0.6128823148093598,
   0.657667566592024,
   0.671962936089332,
   0.6544332680181508,
   0.6424974401850525,
   0.6506004515587138,
   0.6606141161824564,
   0.6970086076079962,
   0.7232282949790836,
   0.688168958836699,
   0.6480912804231354,
   0.6480912804231354,
   0.6659202074370985,
   0.6890552257057037,
   0.7310435573693264,
   0.7796616256114053,
   0.7885012743827025,
   0.7851058363780972,
   0.8130980574871716,
   0.8368200836819994,
   0.8397666332724318,
   0.80529430505627,
   0.8017607475396371,
   0.8014614885968552,
   0.7761165581354312,
   0.7885012743827025,
   0.7821592867876648,
   0.7793623666686234,
   0.7992515764040364,
   0.7612456906712195,
   0.7540174362071994,
   0.7602097943308461,
   0.7572632447404137,
   0.7362000191525775,
   0.7454770463786842,
   0.7579998821380274,
   0.7493098628381212,
   0.7572632447404137,
   0.7426801262596427,
   0.7039260931698932,
   0.6769697684011922,
   0.6936131696033909,
   0.7143886462077864,
   0.7157122915316227,
   0.7348648638694,
   0.7314809358241581,
   0.702901706788861,
   0.7276481193647211,
   0.7139512677529547,
   0.7195451079910375,
   0.7160115504744047,
   0.7160115504744047,
   0.7080581685721121,
   0.7080581685721121,
   0.7080581685721121,
   0.6947986954151775,
   0.6793293100654241,
   0.6887559667629217,
   0.7040757226412842,
   0.6623866499204434,
   0.6598774787848427,
   0.6475042724969127,
   0.6659202074370985,
   0.6793293100654241,
   0.6918521458247451,
   0.6482409098945041,
   0.6497141846897314,
   0.6676927411750855,
   0.6834498755082796,
   0.6834498755082796,
   0.6676927411750855,
   0.6464683761565171,
   0.6227578599210304,
   0.590633563409737,
   0.616266242854624,
   0.5879862727620866,
   0.6139182111497332,
   0.6093487572927048,
   0.5879862727620866,
   0.5760504449289883,
   0.5700077162767325,
   0.5969755510047747,
   0.5816442851670711,
   0.5585207768578071,
   0.5539513230007564,
   0.5778229786669753,
   0.5845908347575035,
   0.5816442851670711,
   0.5624917128292717,
   0.565587891891095,
   0.578260357121807,
   0.5966762920619928,
   0.6158288643997922,
   0.6115586694855235,
   0.6093487572927048,
   0.5894595475573139,
   0.590633563409737,
   0.5854771016264859,
   0.5779610981790251,
   0.5937297424715604,
   0.5816442851670711,
   0.5726665168837242,
   0.5686840709529184,
   0.5791466239908116,
   0.5862137390240996,
   0.5876870138193269,
   0.5952030172667877,
   0.6200990593140387,
   0.6084624904237224,
   0.60551594083329,
   0.5969755510047747,
   0.5938793719429514,
   0.5879862727620866,
   0.5627909717720536,
   0.551154402881715,
   0.5290552809535054,
   0.5106393460133196,
   0.5072439080087143,
   0.5356850175319616,
   0.5433391404914945,
   0.5568978725911888,
   0.5937297424715604,
   0.6040426660380627,
   0.6249677721138491,
   0.594466379869174,
   0.5661748998173177,
   0.5828298109788355,
   0.569420708350532,
   0.5700077162767325,
   0.5664741587600997,
   0.5763497038717702,
   0.5893099180859229,
   0.5848900937002854,
   0.5739901622075605,
   0.5854771016264859,
   0.5938793719429514,
   0.5924060971477463,
   0.5974129294596064,
   0.5932923640167287,
   0.5981495668572201,
   0.6041922955094536,
   0.581943544109853,
   0.5803206398432348,
   0.5312651931463241,
   0.5395178339913986,
   0.5336247348105339,
   0.5336247348105339,
   0.5256598429489001,
   0.5322895795273785,
   0.5375956707820206,
   0.5377453002534116,
   0.5318522010725468,
   0.5574848805174115,
   0.5468842079674685,
   0.5698580868053416,
   0.5739901622075605,
   0.5759008154575973,
   0.5703069752195145,
   0.5548375898697611,
   0.5451116742294815,
   0.5352361291178109,
   0.49590659806117987,
   0.50091343037304,
   0.4995897850492037,
   0.5126996287347474,
   0.5141729035299747,
   0.5140232740585837,
   0.5165324451941844,
   0.5184430984442212,
   0.5184430984442212,
   0.4735082171901661,
   0.43225652292415706,
   0.43608933938357186,
   0.4552419117213713,
   0.4624586562260502,
   0.4590747281808083,
   0.44198243856443664,
   0.4359397099122031,
   0.4132535800577486,
   0.3790690008250275,
   0.3832010762272464,
   0.3933643703223577,
   0.40957039306972476,
   0.4185596713123907,
   0.4301962402027293,
   0.44050916376923155,
   0.4403595342978406,
   0.44050916376923155,
   0.44198243856443664,
   0.44198243856443664,
   0.4436053428310549,
   0.4340290566621441,
   0.4527327405857706,
   0.4416831796216547,
   0.4478755377453014,
   0.4773410336496031,
   0.4885402240850878,
   0.49207378160174287,
   0.5165324451941844,
   0.5831175599622762,
   0.6193624219164251,
   0.5816442851670711,
   0.5701573457481235,
   0.5894595475573139,
   0.6061029487595126,
   0.6386646237256155,
   0.6716636771465723,
   0.673873589339391,
   0.6547210170015916,
   0.6366043410041877,
   0.6762331310036007,
   0.6880193293653081,
   0.6774071468560239,
   0.6762331310036007,
   0.6939124285461729,
   0.6970086076079962,
   0.702901706788861,
   0.6998055277270376,
   0.6803536964464563,
   0.6547210170015916,
   0.6697530238965133,
   0.6525111048087728,
   0.6582545745182466,
   0.6598774787848427,
   0.6140563306618052,
   0.509753079144315,
   0.47483186251400245,
   0.5296422888797281,
   0.5536520640579967,
   0.549381869143728,
   0.5496811280865099,
   0.5420154951676581,
   0.49737987285638496,
   0.5050339958158956,
   0.5200660027108173,
   0.53302621692497,
   0.5362720254581843,
   0.5395178339913986,
   0.5421651246390491,
   0.5395178339913986,
   0.5275820061582781,
   0.5356850175319616,
   0.549232239672337,
   0.549232239672337,
   0.5358346470033526,
   0.5358346470033526,
   0.5392185750486167,
   0.5358346470033526,
   0.5358346470033526,
   0.5461475705698549,
   0.5536520640579967,
   0.5601436811244032,
   0.5524780482055514,
   0.5614673264482395,
   0.565587891891095,
   0.5355353880605707,
   0.5129988876775293,
   0.5094538202015331,
   0.4948707017207843,
   0.4898638694089241,
   0.4850066665684549,
   0.47911356738759014,
   0.48927686148270144,
   0.49354705639697016,
   0.4961943470446206,
   0.4961943470446206,
   0.5199163732394263,
   0.5347987506629792,
   0.5347987506629792,
   0.5347987506629792,
   0.5346491211915883,
   0.5545383309269791,
   0.5545383309269791,
   0.5510047734103463,
   0.5287560220107235,
   0.5281690140845008,
   0.5281690140845008,
   0.5361223959867933,
   0.5361223959867933,
   0.5347987506629792,
   0.5356850175319616,
   0.5281690140845008,
   0.5346491211915883,
   0.524186568153695,
   0.5165324451941844,
   0.5088668122753326,
   0.5068065295538826,
   0.5069561590252736,
   0.5023867051682451,
   0.47292120926394343,
   0.484707407625673,
   0.46408156049266847,
   0.4590747281808083,
   0.4590747281808083,
   0.4571525649714081,
   0.4552419117213713,
   0.4548045332665396,
   0.45641592757381666,
   0.4446297292120871,
   0.417972663386168,
   0.4010300032412095,
   0.41546349225056733,
   0.4522953621309389,
   0.4522953621309389,
   0.4688006438210879,
   0.46260828569744117,
   0.47439448405917073,
   0.4891272320113105,
   0.4789639379161992,
   0.4712983049973474,
   0.46378230154988653,
   0.47144793446873834,
   0.47424485458777976,
   0.47424485458777976,
   0.49207378160174287,
   0.5199163732394263,
   0.5445246663032588,
   0.5617550754316802,
   0.5623535933172219,
   0.5841534563026718,
   0.6046296739642854,
   0.6061029487595126,
   0.5912205713359597,
   0.5845908347575035,
   0.5716306205433508,
   0.5642642465672587,
   0.5536520640579967,
   0.5576345099888025,
   0.565737521362486,
   0.5642642465672587,
   0.5734031542813378,
   0.5734031542813378,
   0.5760504449289883,
   0.5760504449289883,
   0.5760504449289883,
   0.5778229786669753,
   0.5735412737933876,
   0.5735412737933876,
   0.5735412737933876,
   0.5735412737933876,
   0.5732535248099468,
   0.5732535248099468,
   0.5732535248099468,
   0.5437880289056451,
   0.5470223274795183,
   0.5661748998173177,
   0.5583711473864161,
   0.5583711473864161,
   0.5583711473864161,
   0.5738405327361695,
   0.5703069752195145,
   0.5703069752195145,
   0.5738405327361695,
   0.5738405327361695,
   0.5660367803052679,
   0.565887150833877,
   0.5660367803052679,
   0.5564604941363571,
   0.5624917128292717,
   0.5739901622075605,
   0.5703069752195145,
   0.5703069752195145,
   0.5523284187341604,
   0.5523284187341604,
   0.5510047734103463,
   0.551154402881715,
   0.5611680675054576,
   0.5611680675054576,
   0.5611680675054576,
   0.5611680675054576,
   0.549531498615119,
   0.565737521362486,
   0.5773740902528246,
   0.6044800444928944,
   0.5997724711238162,
   0.6115586694855235,
   0.63026235340915,
   0.6452943603040939,
   0.6835995049796706,
   0.6725499440155547,
   0.6812399633154609,
   0.672112565560723,
   0.6927384126937275,
   0.6911155084271314,
   0.6909658789557405,
   0.6835995049796706,
   0.6889055962343127,
   0.6930261616771682,
   0.6787423021392014,
   0.6774071468560239,
   0.6774071468560239,
   0.6735858403559503,
   0.6666568448346899,
   0.657667566592024,
   0.6659202074370985,
   0.6659202074370985,
   0.6486782883493358,
   0.6209853261830434,
   0.6628240283752751,
   0.6087617493664821,
   0.6028686501856395,
   0.6028686501856395,
   0.6028686501856395,
   0.5884236512169183,
   0.5748764290765429,
   0.5561612351935974,
   0.5701573457481235,
   0.6282020706877223,
   0.6544332680181508,
   0.6665072153632989,
   0.6161281233425742,
   0.6161281233425742,
   0.6161281233425742,
   0.623494497318644,
   0.623494497318644,
   0.6093487572927048,
   0.5999221005952071,
   0.5997724711238162,
   0.5878366432906956,
   0.5878366432906956,
   0.5878366432906956,
   0.6007968575048706,
   0.659440100330011,
   0.6751972346632051,
   0.657667566592024,
   0.6170028802522154,
   0.5816442851670711,
   0.6228959794330802,
   0.6227578599210304,
   0.6227578599210304,
   0.6228959794330802,
   0.6228959794330802,
   0.6246685131710672,
   0.6326218950733598,
   0.642934818639862,
   0.646618005627908,
   0.6536966306205372,
   0.6536966306205372,
   0.6539843796039779,
   0.6541340090753689,
   0.657667566592024,
   0.657517937120633,
   0.657667566592024,
   0.657667566592024,
   0.657517937120633,
   0.657517937120633,
   0.657517937120633,
   0.657517937120633,
   0.6460309977016854,
   0.6084624904237224,
   0.6164158723260149,
   0.64691726457069,
   0.6778560352701968,
   0.6958230817962097,
   0.6903788710295178,
   0.6749094856797644,
   0.6402875279922116,
   0.6659202074370985,
   0.6812399633154609,
   0.702901706788861,
   0.7086451764983126,
   0.7003925356532603,
   0.7090825549531443,
   0.709819192350758,
   0.7105558297483716,
   0.7204313748600422,
   0.7295702825740991,
   0.738697680328837,
   0.7708219768401303,
   0.727947378307503,
   0.7272107409098894,
   0.7143886462077864,
   0.6794789395367928,
   0.6690163864988996,

### Grid Search

In [ ]:
# _ = optimize_parameters(
#     ohlcv=ohlcv_test,
#     mid_predicts=mid_pred,
#     spread_predicts=spread_pred,
#     position_size=100.0,
#     alpha_range=(0, 5, 0.1),
#     beta_range=(0, 5, 0.1),
#     gamma_range=(0.1, 0.1, 0.1),
#     epsilon_range=(0.0, 0.0, 0.001),
#     max_position=0.02,
#     position_qty=0.002,
# )